---
- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: relay_init_system == 'systemd'

- name: restart systemd relay instances
  ansible.builtin.systemd_service:
    name: "socat-{{ item.0.name }}-{{ item.1 }}"
    enabled: true
    state: restarted
  loop: "{{ relays | subelements('protocols') }}"
  loop_control:
    label: "{{ item.0.name }}-{{ item.1 }}"
  when: relay_init_system == 'systemd'

- name: restart OpenRC relay instances
  ansible.builtin.command:
    cmd: "rc-service socat-{{ item.0.name }}-{{ item.1 }} restart"
  loop: "{{ relays | subelements('protocols') }}"
  loop_control:
    label: "{{ item.0.name }}-{{ item.1 }}"
  when: relay_init_system == 'openrc'
